# Generated by Django 3.2.7 on 2021-09-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_remove_organisation_parameters'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='parameters',
            field=models.ManyToManyField(blank=True, to='marketplace.Parameter'),
        ),
    ]
